# -*- coding: utf-8 -*-
"""AtualizaBDMFBG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iT-q3fgrmXMzLRU_F3pURWzsrIKBRJec
"""

################################################################################
#
# Atualização do banco de dados do mercado físico de boi gordo
#
# Importa última cotação em arquivo '.csv', edita os dados de preços diários da 
# @ de boi nas diferentes praças e inclui no BDMFBG.csv.
#
################################################################################

# Importando os pacotes 
import pandas as pd
import numpy as np
import csv
import os
from os import listdir
from os.path import isfile, join

# Diretorio
path = "/home/ubuntu/DadosMF/"

# Recuperando lista de ficheiros CSV do diretorio
ficheiros = [f for f in listdir(path) if (isfile(join(path, f)) and f.endswith('.csv')) ]
ficheiros.sort()

# Definindo variáveis globais
datas = []
Pracas = []
df_valores = pd.DataFrame()

# Recuperando as datas e valores para cada ficheiro
for item in ficheiros:
    vard = item[0:8]
    data = int(vard)
    datas.append(data)
    preco = []
    with open(path + item, encoding = 'latin-1') as f:
        reader = csv.reader(f, delimiter = ';')
        for row in reader:
            valor = row[1]
            praca = row[0]
            preco.append(valor)
            Pracas.append(praca)
            Pracas = Pracas[0:32]                            
    df = pd.DataFrame(preco)
    dft = df.T
    df_valores = pd.concat([df_valores, dft], ignore_index=True)
df_valores.columns = Pracas
df_datas = pd.concat([pd.DataFrame([i], columns=['Data']) for i in datas], ignore_index=True)

# Unindo datas e valores num unico dataframe
mfbg = df_datas.join(df_valores)
mfbg.set_index('Data', inplace = True)

# Salvando dataframe como arquivo '.csv'
mfbg.to_csv("/home/ubuntu/Python/BDMFBG.csv", sep = ";")